### ISSUE TITLE
diagnosed vertical diffusion tendency is wrong in ocean_z

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6-examples#162] opened 2017-09-19 20:41 UTC
The vertical sum of OSALTDIFF should vanish.  It does not vanish when viewed in ocean_z.  
There is also a problem with OPOTTEMPDIFF not vanishing.  

Could there be something amiss with the vertical regridding of vertical diffusion?

**Comment by ashao** [comment] 2017-09-20 12:40
At least part of the problem is that the source layer thicknesses offered
to the remapping routines are not consistent with those stored in the
diagnostic remapper. Fixing that problem is a step in resolving the issue
that you brought up, but the remapped vertical diffusive tendencies still
do not sum to zero. I'll take a look at this more today.

**Closed** 2017-09-22 01:55 UTC
